-- docs/sql/initial-schema.sql
-- Simplified HR System Setup (No RLS Blockers)

-- 1. CLEAN REBUILD
DROP TABLE IF EXISTS jobhistory, employee, job, department, UserModule_Rights, users CASCADE;

-- 2. CREATE TABLES
CREATE TABLE department (
    deptcode TEXT PRIMARY KEY,
    deptname TEXT,
    record_status TEXT DEFAULT 'ACTIVE',
    stamp TEXT
);

CREATE TABLE job (
    jobcode TEXT PRIMARY KEY,
    jobdesc TEXT,
    record_status TEXT DEFAULT 'ACTIVE',
    stamp TEXT
);

CREATE TABLE employee (
    empno TEXT PRIMARY KEY,
    lastname TEXT,
    firstname TEXT,
    gender TEXT,
    birthdate DATE,
    hiredate DATE,
    sepdate DATE,
    record_status TEXT DEFAULT 'ACTIVE',
    stamp TEXT
);

CREATE TABLE jobhistory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empno TEXT REFERENCES employee(empno),
    jobcode TEXT REFERENCES job(jobcode),
    deptcode TEXT REFERENCES department(deptcode),
    effdate DATE,
    salary DECIMAL,
    record_status TEXT DEFAULT 'ACTIVE',
    stamp TEXT
);

CREATE TABLE users (
    id UUID PRIMARY KEY,
    username TEXT,
    email TEXT,
    user_type TEXT DEFAULT 'USER',
    record_status TEXT DEFAULT 'ACTIVE'
);

CREATE TABLE UserModule_Rights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId" UUID REFERENCES users(id),
    module_name TEXT,
    view_right INT DEFAULT 0,
    add_right INT DEFAULT 0,
    edit_right INT DEFAULT 0,
    del_right INT DEFAULT 0
);

-- 3. DISABLE RLS (TEMPORARY FOR QUICK START)
ALTER TABLE employee DISABLE ROW LEVEL SECURITY;
ALTER TABLE job DISABLE ROW LEVEL SECURITY;
ALTER TABLE department DISABLE ROW LEVEL SECURITY;
ALTER TABLE jobhistory DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE UserModule_Rights DISABLE ROW LEVEL SECURITY;

-- 4. SEED DATA
INSERT INTO department (deptcode, deptname) VALUES ('IT', 'Information Technology'), ('HRD', 'Human Resources');
INSERT INTO job (jobcode, jobdesc) VALUES ('DEV1', 'Developer'), ('OFF1', 'Officer');
